### ISSUE TITLE
Popdisanie ziadosti - mätúci podpisový priestor

### ISSUE THREAD

**Issue by 4ae16e** [marsher/volby-zo-zahranicia#61]
Text "Tu sa prosím podpíšte" by bolo zmeniť na podpíšte sa k dolnému okraju, pretože je to mätúce.
Pri prvom testovaní som sa podpísal cez ten text a tesne pod neho.. a bolo to v pdf 10cm nad čiarou podpis. Prípadne dať na spodok tie vodiace čiary s textom podpis a cele to posunúť aby to bolo aspoň v tej oblasti.

**Comment by adamliesko** [comment]
Neda sa to automaitcky cropovat?

**Comment by kubocob** [comment]
Myslim, ze by stacilo ak by sme zmensili vysku canvasu (aspon ako easy-fix, neskor sa moze spravit nieco rozumnejsie ako cropping - aby mal pouzivatel vacsi canvas)

``` css
#sign .signature-pad canvas {
    position: relative;
    width: 100%;
    height: 160px; /* povodne height: 592px; */
    z-index: 2;
}
```

![image](https://cloud.githubusercontent.com/assets/7217565/11740932/167a8cc4-9ff6-11e5-939b-1a3bb0481f5e.png)
